name: Publish Latest Dokka Docs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  publish_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Generate Dokka
        run: |
          chmod +x ./gradlew
          ./gradlew :exekutor-core:dokkaHtml

      - name: Copy generated docs to branch folder
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r exekutor-core/build/dokka/* docs/

      - name: Push to `docs` branch (GitHub Pages)
        run: |
          git fetch origin docs || true
          git switch --create docs || git checkout docs

          git add .
          git commit -m "📚 Update GitHub Pages documentation" || echo "No changes"
          git push --force origin docs
