name: Generate and Publish Documentation

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Generate Dokka documentation
        run: |
          chmod +x ./gradlew
          ./gradlew :exekutor-core:dokkaHtml

      - name: Copy generated docs to top-level /docs folder
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r exekutor-core/build/dokka/* docs/

      - name: Commit and push updated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --quiet --cached || git commit -m "📚 Update Dokka documentation"
          git push origin HEAD:main
