name: Documentation Generation

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.job }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Generate Dokka docs
        run: ./gradlew :exekutor-core:dokkaGenerate

      - name: Copy docs to top-level folder
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r exekutor-core/build/dokka/html/* docs/

      - name: Commit and push documentation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --quiet --cached || git commit -m "📚 Update Dokka documentation"
          git push origin HEAD:refs/heads/${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}
